<?php 
$_code= $this->getMethodCode();
$data_bank = $this->getBankconfig();
// print_r($data_bank);
?>
<ul class="form-list" id="payment_form_<?php echo $_code;?>" style="display:none;">
	  <li class="<?php echo $_code;?>_epay_bank">
        <label for="<?php echo $_code;?>_epay_bank" class="required"><em>*</em><?php echo $this->__('เลือกธนาคาร') ?></label>
        <div class="input-box">
          <select id="<?php echo $_code;?>_epay_bank" name="payment[epay_bank]" class="required-entry">
            <option value=""><?php echo $this->__('--Please Select--')?></option>
            <?php foreach ($data_bank as $bank_key => $bank_value): ?>
                <option value="<?php echo $bank_value ?>">
                <?php if($bank_value == 'krungsri'){ 
                    echo $this->__('ธนาคารกรุงศรี'); 
                }else if($bank_value == 'scb'){ 
                    echo $this->__('ธนาคารไทยพาณิชย์'); 
                }?></option>
            <?php endforeach ?>
          </select>
        </div>
    </li>
</ul>